dist: trusty
sudo: required
language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  app:
    master: brainst0rm
    dev: bubblerise
  api_key:
    master:
      secure: Owuf6IVXmQCrXb7LHSJYk9sMriwc5bGxt54/c6+okt2Tz/6dehrW5F71TfCSBFb8K7na/xFRRKC7hcDamOIFs/FUk3h1rCalLgRFyM1xDllG5SUY20qhLvSF974mgLOiqX/izP4ZOxiaqwuszkuzCJ8icj0ycW8hyaUH3m8mbMskvbaFnOmTbigzqaJ6HQy3sJQ/PXf6ubT9zypAbAL/3/V+PjyttYou1D4Zm9kPS5cPeSWzVFda7vHHyUpwBX47hNFZzO39yOcH4maKxtpulb9nUrdF1RWYcJomhBUqcyVo+Cv9G2VhuT2P40NbOOtBhV9F5IvJyCpHFj1WnZV/XffkpIyk7OfLvBbhhUPxFXxZHd1YBBI06mkUbEU31D0DXGnyvXJozkikeYp6DNWoo1PqQKwd3TXaG3y7DGh1JxcTiCcitdLZJXrVJb8Vcm1asZPdh8wikQxGxenEqWOt7R3bODnSSbr7molmWr94rNk7hpkvF5rXAqOyfjy1DzdbnSKlGhYTL2Py9fP4fTydSpe3AUcSIszkTtW1T4oESQ23KlnNZF55u1b+6y2Sjb8L7UyP8xjFvu7zgM0eH4vtEAWlU+Of/3b4Zb6QDlooYWak6ma+sb0vFKKA+TiXqwcKsxq368OUYxJeVyK0K9yMSwTRlqaXe7qbfSgFRRnJ5dk=
    dev:
      secure: ZoTUr9zqBUKciy/XPikg3ERRd6CfYNLqQmhF3AxZZIRiBmqXw9J24Uvs16r70OxzftSo1UooghKZxzOnO7CEQcQrfPBTu9Z9IVZ9RB8hx61VsxBPsC8z+r0cM/e9Gpqz44GUzjD1QpFNR6U2FsnwLmqbFdWgp/cqL/ZUwODSiEHH4SFQ3uTyWRTsZJ9gULZ8eDodS/S8WA9Y5BcYMxElbx6d4xmzmk+8B0Mjp90wTvDn1K7fPN5BDZyFzaJ/cOs6a7CEQ5HaK9SFB9IFaUyBOIza2jha9uP8f8IOvoDYsqhLjjg4d98oMmQihuAsbM4x6Du+XhgoYxwMf4YDZbOgNjsAPmiF77mTL4Fss2jl+WS94TdSkN5TJhUtwqZGpoNA9xpNIR/tkfcCy0XbrTUScv4/JSIoG5O3HLboTp15h1gZuHpvi4q6NZcZyK9/R9D6Z8HDUm4EXxd5IMWJv60430cyfZobEC3KN6xY+y6oq85pytS0IOslgg1sqc2P0LuGfkjseAQ8CF1BkqYzyqJxJMn8FTEwqkJaLjnl+qcimDVCZu3mzE9kpbVM++ijaqOLBstxKDlJuqNerGyib8aXzJbZQqEDUsJWRfTjQz7u1WjBRMnxRtdsXvYYMy5CA7uzYfdfvIfXUgsK929rqrOmXKe7sg6bf0PXkqjxTVsSD9s=
script:
- npm test
