dist: trusty
sudo: required

language: node_js
node_js:
  - '7'

branches:
  only:
    - master
    - dev

deploy:
  provider: heroku
  
  app:
    master: brainst0rm
    dev: bubblerise
  
  api_key:
    master:
      secure: Owuf6IVXmQCrXb7LHSJYk9sMriwc5bGxt54/c6+okt2Tz/6dehrW5F71TfCSBFb8K7na/xFRRKC7hcDamOIFs/FUk3h1rCalLgRFyM1xDllG5SUY20qhLvSF974mgLOiqX/izP4ZOxiaqwuszkuzCJ8icj0ycW8hyaUH3m8mbMskvbaFnOmTbigzqaJ6HQy3sJQ/PXf6ubT9zypAbAL/3/V+PjyttYou1D4Zm9kPS5cPeSWzVFda7vHHyUpwBX47hNFZzO39yOcH4maKxtpulb9nUrdF1RWYcJomhBUqcyVo+Cv9G2VhuT2P40NbOOtBhV9F5IvJyCpHFj1WnZV/XffkpIyk7OfLvBbhhUPxFXxZHd1YBBI06mkUbEU31D0DXGnyvXJozkikeYp6DNWoo1PqQKwd3TXaG3y7DGh1JxcTiCcitdLZJXrVJb8Vcm1asZPdh8wikQxGxenEqWOt7R3bODnSSbr7molmWr94rNk7hpkvF5rXAqOyfjy1DzdbnSKlGhYTL2Py9fP4fTydSpe3AUcSIszkTtW1T4oESQ23KlnNZF55u1b+6y2Sjb8L7UyP8xjFvu7zgM0eH4vtEAWlU+Of/3b4Zb6QDlooYWak6ma+sb0vFKKA+TiXqwcKsxq368OUYxJeVyK0K9yMSwTRlqaXe7qbfSgFRRnJ5dk=
    dev:
      secure: Hqi1iyGS1gPYM2Okg0l84foWFismdmI5/L0IzsSvbRGZazFcGTIiKUQ9+blHBq3zdCiWpPp+bQ06d6y0Sjk2DlcIJHKdoO5oIhbgvbC87Tjxn298gJ9KSS9JY+pnrUWRLdnR1OhoMTBA/QyOsPUJZ5R+qxeln0tOIPtq1LPH5sKi09RBnb1SDlDMgALffdfGMyHlnDoJcQRGCR/5EVbYZxxpB47gz1fyPWSJPESUb/QOnEI8XPF7C93bBc27Yn9Kir1+Cm3OZT26UAQIrII1Tgdtizxr7aE8j5hqPbfKb3TzvACT1VD7D8x39kIBRux0lxY1T2JxY0qFnUHzntCUKNwOYvmjfV/y5aIuuVGCpSXzgsFGI8lN/ZLvyUGyUHtsRUKUFn4yOg1ct5Ih2TzqrKfVVHxGOgdB8gskGx77xsh1TDhGx64D4hqBiPJuyO+Q8YbmpO7LZN52FWJK93qLFPKiZsdsfAxNub06KqWFxCdgk12DtkS7VCq5KO3Yo0i++Ce2q3IgejLc79mFaTmOgtvrNNaxcp1nM8CcjH8jhi0b4jkG7CR+NWn1V45Jf060oDryymisxBWdbX2rUYLT2UiliH4Naf/5X8I0bAXCCnwIW1H6WwtiEqm6De5+sckxacbIZmBZPrjZyxg3SM1zoFNx5Y+CXI4VtargMq7eNB8=

script:
  - echo "Hello World!"
