dist: trusty
sudo: required

language: node_js
node_js:
  - '7'

branches:
  only:
    - master
    - dev

deploy:
  provider: heroku
  
  app:
    master: brainst0rm
    dev: bubblerise
  
  api_key:
    master:
      secure: Owuf6IVXmQCrXb7LHSJYk9sMriwc5bGxt54/c6+okt2Tz/6dehrW5F71TfCSBFb8K7na/xFRRKC7hcDamOIFs/FUk3h1rCalLgRFyM1xDllG5SUY20qhLvSF974mgLOiqX/izP4ZOxiaqwuszkuzCJ8icj0ycW8hyaUH3m8mbMskvbaFnOmTbigzqaJ6HQy3sJQ/PXf6ubT9zypAbAL/3/V+PjyttYou1D4Zm9kPS5cPeSWzVFda7vHHyUpwBX47hNFZzO39yOcH4maKxtpulb9nUrdF1RWYcJomhBUqcyVo+Cv9G2VhuT2P40NbOOtBhV9F5IvJyCpHFj1WnZV/XffkpIyk7OfLvBbhhUPxFXxZHd1YBBI06mkUbEU31D0DXGnyvXJozkikeYp6DNWoo1PqQKwd3TXaG3y7DGh1JxcTiCcitdLZJXrVJb8Vcm1asZPdh8wikQxGxenEqWOt7R3bODnSSbr7molmWr94rNk7hpkvF5rXAqOyfjy1DzdbnSKlGhYTL2Py9fP4fTydSpe3AUcSIszkTtW1T4oESQ23KlnNZF55u1b+6y2Sjb8L7UyP8xjFvu7zgM0eH4vtEAWlU+Of/3b4Zb6QDlooYWak6ma+sb0vFKKA+TiXqwcKsxq368OUYxJeVyK0K9yMSwTRlqaXe7qbfSgFRRnJ5dk=
    dev:
      secure: UIPCMhI+ori62gHcdEKs7LOiiCjCjeM4FowFZk4W6VJ0ex474/WjI0q1ZBJfzLImEtvC7cAAyxRhrvy7bL6KEjGol6CuCYseIePrTYd89L0lxi+BPkQHR6bS/ivOA9xVXRQ5azdlQQmXHIvDN+hXDs4LHCVED9VZ+grirAHWTDiHFH7pubig3GsXev6DvuRYBepXzBChAM3xU5EldjndCv2jTn3Y60P+qS33/6fAWoQ2j7qFYLxnCIgz4tP2Pzh4IcGTexZU3f3YvxsmSvPfHVe674Wr7ZabJ0B42Qk2uBAK2jxv4Hb5JSpmX8qxVOQm1toOL6fK1RxkoJtax/bpvWaRPFFo1NypRSJeSYMoox+wheenU4J2BXR/4TGiow5VWJLybky0GwvSDleOlDuyWrnoo+Rz0hiaHtZMwX4Ur9ybjXTmG/Hc5IkSYO2kwXTNXGrykGo4V+bazTORKd8WgReqls4mzO9Zz6Tu7OmyMX/g62hSG377CiHR40LQSN18nuxCIdZb0tJuJCzUjC/dZzat3jX+y3zOwWjeV6S7fI6iI7WzklM8MgnEHFk+C4I/yUooUS0kfmaOJXiL8GLuYw99j6J7luoippdBhDK1sopCipKsfeLO/to0NjNYvhumjoxIJmOqADfR/g1qS2eG+wqx1bsovNx/jFDHE4HOeMM=

script:
  - echo "Hello World!"
